### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by apostoll13th** [netcoresaas/saas-vuejs-tailwindcss#6]
Demo page not working!

**Comment by AlexandroMtzG** [comment]
Hi! Could you clarify if the issue is on the [frontend demo](http://vue.netcoresaas.com) or the [frontend+backend demo](https://demo.netcoresaas.com/)? I'm guessing the frontend+backend demo since I downgraded the Heroku dyno a few days ago. Thanks!

**Comment by AlexandroMtzG** [comment]
Updated to v2.0.0, with Workspaces, OCR, Projects, and Dashboard. I will leave this open until I create the frontend-only version of the [current demo](http://demo.netcoresaas.com/).
